BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `users` (
	`user_email`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`last_login`	INTEGER NOT NULL DEFAULT 0,
	`admin`	INTEGER NOT NULL DEFAULT 0,
	`uid`	INTEGER PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE IF NOT EXISTS `response_logs` (
	`cid`	INTEGER NOT NULL,
	`time`	INTEGER NOT NULL,
	`log_entry`	TEXT NOT NULL,
	`iid`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `implants` (
	`iid`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`implant_key`	INTEGER NOT NULL,
	`cid`	INTEGER NOT NULL,
	`file_hash`	TEXT NOT NULL,
	`filename`	TEXT NOT NULL,
	`callback_url`	TEXT NOT NULL DEFAULT '127.0.0.1',
	`description`	TEXT
);
CREATE TABLE IF NOT EXISTS `implant_logs` (
	`cid`	INTEGER NOT NULL,
	`uid`	INTEGER NOT NULL,
	`time`	INTEGER NOT NULL,
	`log_entry`	TEXT NOT NULL,
	`iid`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `campaigns` (
	`title`	TEXT NOT NULL UNIQUE,
	`created`	TEXT NOT NULL,
	`cid`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`description`	TEXT
);
CREATE TABLE IF NOT EXISTS `campaign_users` (
	`uid`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`cid`	INTEGER NOT NULL,
	`read`	INTEGER NOT NULL DEFAULT 0,
	`write`	INTEGER NOT NULL DEFAULT 0
);
COMMIT;
